# Generated by Django 3.1.7 on 2021-04-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210413_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
